export const FETCH_MOVIE_REQUEST = "FETCH_MOVIES_REQUEST";
export const FETCH_MOVIES_REQUEST_ERROR = "FETCH_MOVIES_REQUEST_ERROR";
export const FETCH_MOVIES_REQUEST_SUCCESS  = "FETCH_MOVIES_REQUEST_SUCCESS";

